#!/usr/bin/env bash
if [[ -z "${DEFAULT_NETWORK_TIMEOUT:-}" ]]; then
    readonly DEFAULT_NETWORK_TIMEOUT=10
fi
if [[ -z "${DEFAULT_SYSTEM_PAUSE_DURATION:-}" ]]; then
    readonly DEFAULT_SYSTEM_PAUSE_DURATION=2
fi
if [[ -z "${DEFAULT_SUDO_TIMEOUT_MINUTES:-}" ]]; then
    readonly DEFAULT_SUDO_TIMEOUT_MINUTES=15
fi
if [[ -z "${SUDO_KEEPALIVE_INTERVAL:-}" ]]; then
    readonly SUDO_KEEPALIVE_INTERVAL=300
fi


if [[ -z "${EXIT_SUCCESS:-}" ]]; then
    readonly EXIT_SUCCESS=0
fi
if [[ -z "${EXIT_GENERAL_ERROR:-}" ]]; then
    readonly EXIT_GENERAL_ERROR=1
fi
if [[ -z "${EXIT_MISSING_COMMAND:-}" ]]; then
    readonly EXIT_MISSING_COMMAND=127
fi
if [[ -z "${EXIT_PERMISSION_DENIED:-}" ]]; then
    readonly EXIT_PERMISSION_DENIED=126
fi
if [[ -z "${EXIT_NETWORK_ERROR:-}" ]]; then
    readonly EXIT_NETWORK_ERROR=2
fi
if [[ -z "${EXIT_FILE_NOT_FOUND:-}" ]]; then
    readonly EXIT_FILE_NOT_FOUND=3
fi
if [[ -z "${EXIT_INVALID_INPUT:-}" ]]; then
    readonly EXIT_INVALID_INPUT=4
fi
if [[ -z "${EXIT_INTERRUPTED:-}" ]]; then
    readonly EXIT_INTERRUPTED=130
fi


if [ -z "${INTERFACE_WIDTH:-}" ]; then
    readonly INTERFACE_WIDTH=72

    readonly INTERFACE_COLOR=214
    readonly INTERFACE_SECONDARY=208
    readonly INTERFACE_ACCENT=51
    readonly INTERFACE_ERROR=10
    readonly INTERFACE_BG_COLOR=0
    readonly INTERFACE_BOLD="--bold"
fi


if [[ -z "${HOMEBREW_PREFIX_ARM:-}" ]]; then
    readonly HOMEBREW_PREFIX_ARM="/opt/homebrew"
fi
if [[ -z "${HOMEBREW_PREFIX_INTEL:-}" ]]; then
    readonly HOMEBREW_PREFIX_INTEL="/usr/local"
fi


if [[ -z "${SYSTEM_RESOLVER_DIR:-}" ]]; then
    readonly SYSTEM_RESOLVER_DIR="/etc/resolver"
fi
if [[ -z "${PAM_CONFIG_DIR:-}" ]]; then
    readonly PAM_CONFIG_DIR="/etc/pam.d"
fi
if [[ -z "${SUDOERS_DIR:-}" ]]; then
    readonly SUDOERS_DIR="/etc/sudoers.d"
fi


if [[ -z "${SUDO_AUTH_MARKER:-}" ]]; then
    readonly SUDO_AUTH_MARKER="/tmp/.bootstrap_sudo_authenticated"
fi
if [[ -z "${SUDO_KEEPALIVE_PID:-}" ]]; then
    readonly SUDO_KEEPALIVE_PID="/tmp/.bootstrap_sudo_keepalive_pid"
fi
if [[ -z "${BOOTSTRAP_TIMEOUT_CONFIG:-}" ]]; then
    readonly BOOTSTRAP_TIMEOUT_CONFIG="/etc/sudoers.d/bootstrap_timeout"
fi


if [[ -z "${DEFAULT_CONNECTIVITY_URL:-}" ]]; then
    readonly DEFAULT_CONNECTIVITY_URL="https://raw.githubusercontent.com"
fi
if [[ -z "${FALLBACK_PING_HOST:-}" ]]; then
    readonly FALLBACK_PING_HOST="github.com"
fi


if [[ -z "${NETWORK_MAX_RETRIES:-}" ]]; then
    readonly NETWORK_MAX_RETRIES=1
fi
if [[ -z "${CURL_CONNECT_TIMEOUT_MULTIPLIER:-}" ]]; then
    readonly CURL_CONNECT_TIMEOUT_MULTIPLIER=2
fi


if [[ -z "${LOADER_CHARS:-}" ]]; then
    readonly LOADER_CHARS='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
fi
if [[ -z "${LOADER_DELAY:-}" ]]; then
    readonly LOADER_DELAY=0.02
fi
if [[ -z "${LOADER_CHAR_COUNT:-}" ]]; then
    readonly LOADER_CHAR_COUNT=10
fi


if [[ -z "${DEFAULT_LOG_LEVEL:-}" ]]; then
    readonly DEFAULT_LOG_LEVEL="INFO"
fi
if [[ -z "${LOG_DATE_FORMAT:-}" ]]; then
    readonly LOG_DATE_FORMAT="+%Y-%m-%dT%H:%M:%SZ"
fi
if [[ -z "${DEBUG_LOG_DATE_FORMAT:-}" ]]; then
    readonly DEBUG_LOG_DATE_FORMAT="+%H:%M:%S"
fi


if [[ -z "${LOG_DIR:-}" ]]; then
    readonly LOG_DIR="tmp/log"
fi
