#!/usr/bin/env bash
get_debug_log_file() {
    if [ -z "${DOTFILES_DEBUG_LOG:-}" ]; then
        local session_id="${DOTFILES_SESSION_ID:-$(date +%Y%m%d-%H%M%S)}"
        DOTFILES_DEBUG_LOG="${DOTFILES_PARENT_DIR:-$PWD}/tmp/debug-${session_id}.log"
        export DOTFILES_DEBUG_LOG
    fi
    echo "$DOTFILES_DEBUG_LOG"
}


write_log() {
    local level="$1"
    local message="$2"
    local debug_file
    debug_file=$(get_debug_log_file)
    

    mkdir -p "$(dirname "$debug_file")"
    

    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $level: $message" >> "$debug_file"
}


debug_log() { write_log "DEBUG" "$1"; }
info_log() { write_log "INFO" "$1"; }
success_log() { write_log "SUCCESS" "$1"; }
warn_log() { write_log "WARN" "$1"; }
error_log() { write_log "ERROR" "$1"; }
command_log() { write_log "COMMAND" "$1"; }
output_log() { write_log "OUTPUT" "$1"; }


get_debug_log_path() {
    local debug_file
    debug_file=$(get_debug_log_file)
    echo "${debug_file#${DOTFILES_PARENT_DIR:-$PWD}/}"
}