#!/bin/sh

ensure_zsh(){
	ensure_sudo
	run "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	run "brew install romkatv/powerlevel10k/powerlevel10k"
	run "source ~/.zshrc"
}

ensure_fonts(){
	ensure_sudo
	run "cp fonts/*.ttf ~/Library/Fonts"
}

ensure_dotfiles(){
	ensure_sudo
	if command -v chezmoi >/dev/null 2>&1; then
		run "chezmoi init --apply brndnblck"
	else
		show_error "Missing Dotfile Manager."
	fi
}
