#!/bin/sh

ensure_dependencies() {
	ensure_sudo
	run "brew bundle --no-lock -d --file=$PARENT_DIR/Brewfile.dependencies"
}

ensure_applications() {
	ensure_sudo
	run "brew bundle --no-lock -d --file=$PARENT_DIR/Brewfile.software"
}

ensure_osx_configuration() {
	ensure_sudo
	source $PARENT_DIR/script/helpers/preferences
}

ensure_updated() {
	ensure_sudo
	run "brew upgrade"
	run "mas upgrade"
}
