#!/bin/sh

LOGPATH="$PARENT_DIR/tmp/log"
LOGFILE=${LOG_FILE:='debug.log'}
LOGLEVEL=${LOG_LEVEL:='info'}

function record_cmd() {
  mkdir -p $LOGPATH

  record "$@"
  eval $@ >> "$LOG_FILE" 2>&1
}

function record() {
  mkdir -p $LOGPATH

  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $@" >> $LOGPATH/$LOGFILE 2>&1
}

run() {
	record_cmd "$@"
}

show_info() {
	ansi --magenta --bold --no-restore --newline
	echo "$1"
	record "$1"
	ansi --reset-color --newline
}

show_error() {
	ansi --red --bold --no-restore --newline
	echo "Error! $1"
	ansi --reset-color --newline
	exit 1
}

show_warn() {
	ansi --yellow --bold --no-restore --newline
	if [ "$1" == "--skip-newline" ]; then
		echo "Warning! $2"
	else
		echo "Warning! $1"
		ansi --reset-color --newline
	fi
}

ensure_set() {
	if [ -z "$1" ]; then
		show_error "$2"
	fi
}

check_latest() {
	latest=`git log HEAD..origin/master --oneline`
	if [ -n "$latest" ]; then
		if [ "$1" == "--abort" ]; then
			ansi --red --bold --no-restore --newline
			echo "Error! Your verison of the development environment is out-of-date."
			ansi --white --bold --no-restore --newline
			echo "Please update first (Run ./script/sync)."
			ansi --reset-color --reset-attrib --newline
			exit 1
		else
			show_warn "You're running an older verison of the development environment."
		fi
	fi
}

show_loader() {
	($1) &
	local pid=$!
	[ -n "$2" ] && message="$2" || message='Please wait...'
	local length=${#message}
	local i=0
	local loader='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
	ansi --hide-cursor --no-restore
	while(ps a | awk '{print $1}' | grep -q "${pid}");  do
		i=$(( (i+1) % 10 ))
		ansi --blue-intense $(printf "\r   ${loader:$i:1}")
		ansi --bold --no-restore
		if [ -n "$message" ]; then
			printf " $message"
		else
			printf ' Please wait...'
		fi
		ansi --reset-attrib
		sleep .02
	done

	ansi --green --bold --no-restore
	printf " \r✓ "
	ansi --white --faint --no-restore
	printf " $message\n"
	ansi --reset-attrib --reset-color
	ansi --show-cursor
}
